target: "Travel Time to Work"

perturbations: 
  - name: Age
    type: integer
    size: 1

rename:
  Age: Age
  'Employment status of parents': 'Parents employment'
  'Class of worker': Employment
  'Educational attainment': Highest Education
  'Marital status': Married
  Occupation: Work
  Sex: Self-reported sex
  'Recorded race': Self-reported race
  'Place of birth': Place of birth
  'Travel Time to Work': Travel time

recode:
  'Educational attainment': 
    'No schooling completed': 'No schooling'
    'Nursery school, preschool': Preschool
    'Kindergarten': Kindergarten
    'Grade 1': 1st grade
    'Grade 2': 2nd grade
    'Grade 3': 3rd grade 
    'Grade 4': 4th grade 
    'Grade 5': 5th grade
    'Grade 6': 6th grade
    'Grade 7': 7th grade
    'Grade 8': 8th grade
    'Grade 9': 9th grade
    'Grade 10': 10th grade
    'Grade 11': 11th grade
    '12th grade - no diploma': '12th grade, no diploma'
    'Regular high school diploma': 'High school diploma'
    'GED or alternative credential': 'GED'
    'Some college, but less than 1 year': 'Less than 1 year of college'
    '1 or more years of college credit, no degree': 'At least 1 year of college, no degree'
    "Associate's degree": "Associate's degree"
    "Bachelor's degree": "Bachelor's" 
    "Master's degree": "Master's"
    "Professional degree beyond a bachelor's degree": "Professional degree"
    "Doctorate degree": Doctorate
  'Marital status':
    'Never married or under 15 years old': 'Never married'
  'Disability':
    'With a disability': 'True'
    'Without a disability': 'False'
  'Employment status of parents':
    'N/A (not own child of householder, and not child in subfamily)': 'Not applicable'
    'Living with two parents: Both parents in labor force': 'Living with two parents in labor force'
    'Living with mother: In labor force': 'Living with mother in labor force'
    'Living with father: In labor force': 'Living with father in labor force'
    'Living with mother: Not in labor force': 'Living with mother not in labor force'
    'Living with two parents: Father only in labor force': 'Living with two parents, father labor force'
    'Living with father: Not in labor force': 'Living with father not in labor force'
    'Living with two parents: Neither parent in labor force': 'Living with two parents not in labor force'
    'Living with two parents: Mother only in labor force': 'Living with two parents, mother labor force'
  'Lived here 1 year ago':
    ".N/A (less than 1 year old)": "Not applicable"
    "Yes, same house (nonmovers)": "Yes"
    "No, outside US and Puerto Rico": "No, outside US or Puerto Rico"
    "No, different house in US or Puerto Rico": "No, different house in US or Puerto Rico"
  'Recorded race':
    'White alone': 'White'
    'Black or African American alone': 'Black'
    'American Indian alone': 'American Indian'
    'Alaska Native alone': 'Alaska Native'
    'American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races': 'American Indian or Alaska Native or not specified'
    'Asian alone': 'Asian'
    'Native Hawaiian and Other Pacific Islander alone': 'Pacific Island'
    'Some Other Race alone': 'Other'
    'Two or More Races': 'Two or more'
  'State':
    'Alabama/AL': 'Alabama'
    'Alaska/AK': 'Alaska'
    'Arizona/AZ': 'Arizona'
    'Arkansas/AR': 'Arkansas'
    'California/CA': 'California'
    'Colorado/CO': 'Colorado'
    'Connecticut/CT': 'Connecticut'
    'Delaware/DE': 'Delaware'
    'District of Columbia/DC': 'District of Columbia'
    'Florida/FL': 'Florida'
    'Georgia/GA': 'Georgia'
    'Hawaii/HI': 'Hawaii'
    'Idaho/ID': 'Idaho'
    'Illinois/IL': 'Illinois'
    'Indiana/IN': 'Indiana'
    'Iowa/IA': 'Iowa'
    'Kansas/KS': 'Kansas'
    'Kentucky/KY': 'Kentucky'
    'Louisiana/LA': 'Louisiana'
    'Maine/ME': 'Maine'
    'Maryland/MD': 'Maryland'
    'Massachusetts/MA': 'Massachusetts'
    'Michigan/MI': 'Michigan'
    'Minnesota/MN': 'Minnesota'
    'Mississippi/MS': 'Mississippi'
    'Missouri/MO': 'Missouri'
    'Montana/MT': 'Montana'
    'Nebraska/NE': 'Nebraska'
    'Nevada/NV': 'Nevada'
    'New Hampshire/NH': 'New Hampshire'
    'New Jersey/NJ': 'New Jersey'
    'New Mexico/NM': 'New Mexico'
    'New York/NY': 'New York'
    'North Carolina/NC': 'North Carolina'
    'North Dakota/ND': 'North Dakota'
    'Ohio/OH': 'Ohio'
    'Oklahoma/OK': 'Oklahoma'
    'Oregon/OR': 'Oregon'
    'Pennsylvania/PA': 'Pennsylvania'
    'Rhode Island/RI': 'Rhode Island'
    'South Carolina/SC': 'South Carolina'
    'South Dakota/SD': 'South Dakota'
    'Tennessee/TN': 'Tennessee'
    'Texas/TX': 'Texas'
    'Utah/UT': 'Utah'
    'Vermont/VT': 'Vermont'
    'Virginia/VA': 'Virginia'
    'Washington/WA': 'Washington'
    'West Virginia/WV': 'West Virginia'
    'Wisconsin/WI': 'Wisconsin'
    'Wyoming/WY': 'Wyoming'
  'Citizenship':
    "Born in the United States":  "Born in the U.S."
    "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or Northern Marianas": "Born in U.S. territories"
    "Born abroad of U.S. citizen parent or parents": "Born abroad of U.S. citizen parent"
    "U.S. citizen by naturalization": "Naturalized U.S. citizen"
    "Not a U.S. citizen": "Not a U.S. citizen"
  'Travel Time to Work':
    'More than 20 minutes': 'Longer than 20 minutes'
    'Less than 20 minutes': 'Shorter than 20 minutes'