target: species

perturbations: 
  - name: [sepal_length, sepal_width, petal_length]
    type: integer
    size: 1
    scale: 0.1
  - name: petal_width
    type: integer
    size: 1
    scale: 0.1
    frozen_values: [0, 0.1, 0.2]
  - name: [sepal_length, sepal_width, petal_length, petal_width]
    type: round
    decimals: 1
    
transform: 
  - name: [sepal_length, sepal_width, petal_length]
    type: add_normal_noise_and_round
    noise_std: 0.02
    digits: 2
  - name: petal_width
    type: add_normal_noise_and_round
    noise_std: 0.01
    digits: 2

rename:
  sepal_length: Length of Sepal (cm)
  sepal_width: Width of Sepal (cm)
  petal_length: Length of Petal (cm)
  petal_width: Width of Petal (cm)
  species: Kind of Flower

recode:
  species:
    Iris-setosa: Setosa
    Iris-virginica: Virginica
    Iris-versicolor: Versicolor