target: Transported

perturbations: 
  - name: PassengerId
    type: spaceship_titanic_passenger_id
  - name: Cabin
    type: spaceship_titanic_cabin
  - name: Age
    type: integer
    size: 1
    frozen_values: [0, 1]
  - name: [RoomService, FoodCourt, ShoppingMall, Spa, VRDeck]
    type: integer
    size: 5
    frozen_values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    
transform: 
  - name: Age
    type: fillna
    value: 30
  - name: Age
    type: astype
    dtype: int
  - name: [Destination,Cabin]
    type: fillna
    value: 'Unknown'
  - name: [RoomService, FoodCourt, ShoppingMall, Spa, VRDeck]
    type: add_normal_noise_and_round
    noise_std: 0.5
    digits: 2
    frozen_values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  - name: Transported
    type: astype
    dtype: object

rename:
  PassengerId: PassengerID
  HomePlanet: Home Planet
  CryoSleep: Cryo Sleep
  Cabin: Room
  Destination: Destination
  RoomService: RoomService
  FoodCourt: FoodCourt
  ShoppingMall: ShoppingMall
  Spa: Spa
  VRDeck: VRDeck
  Age: Age
  VIP: Very Important Person?
  Name: Name
  Transported: Transported

recode:
  VIP:
    0: "No"
    1: "Yes"
  Transported:
    0: "No"
    1: "Yes"