target: Transported

perturbations: 
  - name: Age
    type: integer
    size: 3
  - name: [RoomService, FoodCourt, ShoppingMall, Spa, VRDeck]
    type: integer
    size: 10
    frozen_values: [0]



transform: 
  - name: [CapitalGain, CapitalLoss]
    type: add_normal_noise_and_round
    noise_std: 10
    digits: 2
    frozen_values: [0]

rename:
  Age: Age
  Workclass: Type of employment
  fnlwgt: Final weight in census
  Education: Highest achieved level of education
  EducationNum: Education in numerical form
  MaritalStatus: Relationship Status
  Occupation: Type of occupation
  Relationship: What this individual is relative to others?
  Race: Self-reported race
  Gender: Self-reported gender
  CapitalGain: Income from investment sources
  CapitalLoss: Losses from investment sources
  HoursPerWeek: Hours worked per week
  NativeCountry: Country of origin
  Income: Yearly Income

recode:
  Income:
    <=50K: Less than 50K
    ">50K": More than 50K