target: Survived

perturbations: 
  - name: Age
    type: integer
    size: 1
  - name: Fare
    type: swap
    size: 1
  - name: PassengerId
    type: integer
    size: 1
  - name: [SibSp, Parch]
    type: integer
    size: 1
    frozen_values: [0, 1]
  - name: Ticket
    type: titanic_ticket_perturbation

transform: 
  - name: Age
    type: fillna
    value: 0
  - name: Age
    type: astype
    dtype: int
  - name: Name
    type: titanic_name_transform
  - name: Fare
    type: add_normal_noise_and_round
    noise_std: 0.01
    digits: 2
  - name: [Embarked, Cabin]
    type: fillna
    value: 'Unknown'

rename:
  PassengerId: Passenger ID
  Survived: Survived
  Pclass: Class
  SibSp: Number of Siblings/Spouses aboard
  Parch: Number of Parents/Children aboard
  Ticket: Ticket Number
  Fare: Fare
  Cabin: Cabin Number
  Embarked: Port of Embarkation

recode:
  Survived:
    0: "Not Survived"
    1: "Survived"
  Sex:
    male: M
    female: F
  Embarked:
    C: Cherbourg
    Q: Queenstown
    S: Southampton
  Pclass:
    1: First
    2: Second
    3: Third
