target: Survived

perturbations: 
  - name: Age
    type: integer
    size: 1
  - name: Fare
    type: swap
    size: 1
  - name: PassengerId
    type: integer
    size: 1
  - name: [SibSp, Parch]
    type: integer
    size: 1
    frozen_values: [0, 1]
  - name: Ticket
    type: integer
    size: 10
    ignore_object: True
  - name: Ticket
    type: astype
    dtype: int
    lazy: True



transform: 
  - name: [CapitalGain, CapitalLoss]
    type: add_normal_noise_and_round
    noise_std: 10
    digits: 2
    frozen_values: [0]

rename:
  Age: Age
  Workclass: Type of employment
  fnlwgt: Final weight in census
  Education: Highest achieved level of education
  EducationNum: Education in numerical form
  MaritalStatus: Relationship Status
  Occupation: Type of occupation
  Relationship: What this individual is relative to others?
  Race: Self-reported race
  Gender: Self-reported gender
  CapitalGain: Income from investment sources
  CapitalLoss: Losses from investment sources
  HoursPerWeek: Hours worked per week
  NativeCountry: Country of origin
  Income: Yearly Income

recode:
  Income:
    <=50K: Less than 50K
    ">50K": More than 50K