name: tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip and package
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Run tests
      run: |
        pytest